## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [10]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [11]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data’: File exists

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [12]:
!pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.2.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Requirement already satisfied: url-normalize>=1.4 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [13]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (KRAS)**
Search ChEMBL for the KRAS target and select the most relevant entry.

In [14]:
target = new_client.target
target_query = target.search("KRAS")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,GTPase KRas,19.0,False,CHEMBL2189121,"[{'accession': 'P01116', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Protein cereblon-KRAS,19.0,False,CHEMBL5483196,"[{'accession': 'P01116', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
2,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/KRAS,18.0,False,CHEMBL5169273,"[{'accession': 'P01116', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
3,[],Homo sapiens,SOS1-KRAS,18.0,False,CHEMBL5465393,"[{'accession': 'Q07889', 'component_descriptio...",PROTEIN COMPLEX,9606
4,[],Homo sapiens,PDE6D/KRAS,17.0,False,CHEMBL4523623,"[{'accession': 'O43924', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

**Reterive Bioactivity data for selected target**

In [15]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL2189121'

**Now retrieve only bioactivity data for target; **GTPase KRas(CHEMBL2189121)** with reported IC 50  values in nM (nanomolar) unit.**

In [16]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [17]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13352855,[],CHEMBL2399318,Inhibition of full-length human KRas4B (amino ...,B,None,None,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,155.0
1,None,None,13352856,[],CHEMBL2399319,Inhibition of full-length human KRas4B (amino ...,B,None,None,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,342.0
2,None,None,14548911,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,1.2
3,None,None,14548912,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,10.0
4,None,None,14548913,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,1.8

In [18]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [19]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [20]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [21]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 8417
-rw------- 1 root root 8618041 Jan 25 10:45 bioactivity_raw_data.csv

In [22]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,13352855,[],CHEMBL2399318,Inhibition of full-length human KRas4B (amino acids 1 to 188)-SOS interaction assessed as inhibition of SOS-mediated nucleotide release activity,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL2396593,J Med Chem,2013,,CHEMBL2396992,,CHEMBL2396992,,0,http://www.openphacts.org/units/Nanomolar,1902314,=,1,1,=,,IC50,nM,,155000.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,155.0
,,13352856,[],CHEMBL2399319,Inhibition of full-length human KRas4B (amino acids 1 to 188)-SOS interaction assessed as inhibition of nucleotide exchange activity,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL2396593,J Med Chem,2013,,CHEMBL2396992,,CHEMBL2396992,,0,http://www.openphacts.org/units/Nanomolar,1902314,=,1,1,=,,IC50,nM,,342000.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,342.0
,,14548911,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CC(C)[C@@H]1NC(=O)[C@@H](CC(N)=O)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](Cc2ccc(F)cc2)NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C(=O)C(C)(C)COC1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '4.24', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218635,,CHEMBL3218635,5.92,0,http://www.openphacts.org/units/Nanomolar,2073173,=,1,1,=,,IC50,nM,,1200.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,1.2
,,14548912,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CCCC[C@H]1NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[C@@H](CCCCN)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](Cc2ccc(F)cc2)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C(=O)C(C)(C)COC1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '3.33', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218636,,CHEMBL3218636,5.00,0,http://www.openphacts.org/units/Nanomolar,2073174,=,1,1,=,,IC50,nM,,10000.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,10.0
,,14548913,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC(=N)N)NC(=O)CNC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[C@H](CCCN)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '4.17', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218637,,CHEMBL3218637,5.75,0,http://www.openphacts.org/units/Nanomolar,2073175,=,1,1,=,,IC50,nM,,1800.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,1.8
,,14548914,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CC(C)C[C@@H]1NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@H](Cc2ccc(F)cc2)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C(=O)C(C)(C)COC1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '4.61', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218638,,CHEMBL3218638,6.70,0,http://www.openphacts.org/units/Nanomolar,2073176,=,1,1,=,,IC50,nM,,200.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,0.2
,,14548915,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@@H]2CCCN2C(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@@H](Cc2ccccc2)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '3.53', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218639,,CHEMBL3218639,5.00,0,http://www.openphacts.org/units/Nanomolar,2073177,=,1,1,=,,IC50,nM,,10000.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,10.0
,,14548916,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CC(C)C[C@@H]1NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](c2ccccc2)NC(=O)[C@@H](Cc2ccccc2)NC(=O)[C@H](CCCN)NC(=O)[C@@H]2CCCN2C(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C(=O)C(C)(C)COC1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '3.92', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218640,,CHEMBL3218640,5.00,0,http://www.openphacts.org/units/Nanomolar,2073178,=,1,1,=,,IC50,nM,,10000.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,10.0
,,14548917,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V mutant (unknown origin) assessed as disruption of interaction with GST-tagged Raf-RBD after overnight incubation by HTRF assay,B,P01116,G12V,BAO_0000190,BAO_0000019,assay format,CCCC[C@H]1NC(=O)[C@H](Cc2ccc(F)cc2)NC(=O)[C@H](CCCN=C(N)N)NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[C@H](CCCN=C(N)N)NC(=O)[C@H](CCCN=C(N)N)NC(=O)[C@H](CCC(N)=O)NC(=O)C[C@@H](CCc2ccccc2)NC(=O)[C@@H]2CCCCN2C(=O)C(=O)C(C)(C)COC1=O,,,CHEMBL3217533,Medchemcomm,2013,"{'bei': '4.14', 'le': None, 'lle': None, 'sei': None}",CHEMBL3218641,,CHEMBL3218641,6.16,0,http://www.openphacts.org/units/Nanomolar,2073179,=,1,1,=,,IC50,nM,,700.0,CHEMBL2189121,Homo sapiens,GTPase KRas,9606,,,IC50,uM,UO_0000065,,0.7

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KRAS target.**

**Inspect Missing Values**

In [23]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [25]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13352855,[],CHEMBL2399318,Inhibition of full-length human KRas4B (amino ...,B,None,None,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,155.0
1,None,None,13352856,[],CHEMBL2399319,Inhibition of full-length human KRas4B (amino ...,B,None,None,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,342.0
2,None,None,14548911,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,1.2
3,None,None,14548912,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,10.0
4,None,None,14548913,[],CHEMBL3223233,Inhibition of recombinant HA-tagged K-Ras G12V...,B,P01116,G12V,BAO_0000190,...,Homo sapiens,GTPase KRas,9606,None,None,IC50,uM,UO_0000065,None,1.8

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [26]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [27]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [28]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [29]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL2396992,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,155000.0,inactive
1,CHEMBL2396992,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,342000.0,inactive
2,CHEMBL3218635,CC(C)[C@@H]1NC(=O)[C@@H](CC(N)=O)NC(=O)[C@H](C...,1200.0,intermediate
3,CHEMBL3218636,CCCC[C@H]1NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[...,10000.0,inactive
4,CHEMBL3218637,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC...,1800.0,intermediate

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [30]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL2396992,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,155000.0,inactive
1,CHEMBL2396992,Cc1[nH]c2cc(Cl)cc(Cl)c2c1CCN,342000.0,inactive
2,CHEMBL3218635,CC(C)[C@@H]1NC(=O)[C@@H](CC(N)=O)NC(=O)[C@H](C...,1200.0,intermediate
3,CHEMBL3218636,CCCC[C@H]1NC(=O)[C@@H](Cc2ccc3ccccc3c2)NC(=O)[...,10000.0,inactive
4,CHEMBL3218637,CC1(C)COC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCCNC...,1800.0,intermediate

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [31]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_preprocessed_data.csv  bioactivity_raw_data.csv